public enum PopupName
{
    BUILDING_SELECTION = 0,
    ONLY_ROAD_SELECTION =1,
    COMMERICAL_BUILDING_CONFIG =2,
    COMMERICAL_BUILDING_INFO = 3,
    RESIDENTIAL_BUILDING_CONFIG = 4,
    RESIDENTIAL_BUILDING_INFO = 5,
}
